"""initial schema

Revision ID: 051a7646460e
Revises: 
Create Date: 2026-07-09 02:00:47.975290

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores da revisão, usados pelo Alembic.
revision: str = '051a7646460e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('target_brand', sa.String(length=128), nullable=False),
    sa.Column('phishing_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('not_before', sa.String(length=64), nullable=False),
    sa.Column('not_after', sa.String(length=64), nullable=False),
    sa.Column('pem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', 'fingerprint', name='uq_cert_serial_fp')
    )
    op.create_index(op.f('ix_certificates_fingerprint'), 'certificates', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_certificates_serial_number'), 'certificates', ['serial_number'], unique=False)
    op.create_table('fingerprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dom_hash', sa.String(length=64), nullable=False),
    sa.Column('asset_hash', sa.String(length=64), nullable=False),
    sa.Column('script_hash', sa.String(length=64), nullable=False),
    sa.Column('campaign_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fingerprints_asset_hash'), 'fingerprints', ['asset_hash'], unique=False)
    op.create_index(op.f('ix_fingerprints_campaign_fingerprint'), 'fingerprints', ['campaign_fingerprint'], unique=False)
    op.create_index(op.f('ix_fingerprints_dom_hash'), 'fingerprints', ['dom_hash'], unique=False)
    op.create_index(op.f('ix_fingerprints_script_hash'), 'fingerprints', ['script_hash'], unique=False)
    op.create_table('infrastructures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('asn', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructures_asn'), 'infrastructures', ['asn'], unique=False)
    op.create_index(op.f('ix_infrastructures_ip'), 'infrastructures', ['ip'], unique=False)
    op.create_table('misp_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_uuid', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misp_events_event_uuid'), 'misp_events', ['event_uuid'], unique=False)
    op.create_table('phishing_sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('html_hash', sa.String(length=64), nullable=False),
    sa.Column('js_hash', sa.String(length=64), nullable=False),
    sa.Column('target_brand', sa.String(length=128), nullable=False),
    sa.Column('phishing_type', sa.String(length=64), nullable=False),
    sa.Column('evidence_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_sites_campaign_id'), 'phishing_sites', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_phishing_sites_domain'), 'phishing_sites', ['domain'], unique=False)
    op.create_index(op.f('ix_phishing_sites_html_hash'), 'phishing_sites', ['html_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phishing_sites_html_hash'), table_name='phishing_sites')
    op.drop_index(op.f('ix_phishing_sites_domain'), table_name='phishing_sites')
    op.drop_index(op.f('ix_phishing_sites_campaign_id'), table_name='phishing_sites')
    op.drop_table('phishing_sites')
    op.drop_index(op.f('ix_misp_events_event_uuid'), table_name='misp_events')
    op.drop_table('misp_events')
    op.drop_index(op.f('ix_infrastructures_ip'), table_name='infrastructures')
    op.drop_index(op.f('ix_infrastructures_asn'), table_name='infrastructures')
    op.drop_table('infrastructures')
    op.drop_index(op.f('ix_fingerprints_script_hash'), table_name='fingerprints')
    op.drop_index(op.f('ix_fingerprints_dom_hash'), table_name='fingerprints')
    op.drop_index(op.f('ix_fingerprints_campaign_fingerprint'), table_name='fingerprints')
    op.drop_index(op.f('ix_fingerprints_asset_hash'), table_name='fingerprints')
    op.drop_table('fingerprints')
    op.drop_index(op.f('ix_certificates_serial_number'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_fingerprint'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
