"""Domain exceptions — typed errors from the domain layer."""

from threat_hunting.core.domain.exceptions.domain_exceptions import (
    DomainError,
    ConnectorError,
    ConnectorNotFoundError,
    CollectionError,
    ParseError,
    ExtractionError,
    NormalizationError,
    DetectionError,
    ScoringError,
    CorrelationError,
    DeduplicationError,
    EnrichmentError,
    PersistenceError,
    ExportError,
    ValidationError,
    ConfigurationError,
    OpsecError,
    RuleLoadError,
    EntityNotFoundError,
    DuplicateEntityError,
)

__all__ = [
    "DomainError",
    "ConnectorError",
    "ConnectorNotFoundError",
    "CollectionError",
    "ParseError",
    "ExtractionError",
    "NormalizationError",
    "DetectionError",
    "ScoringError",
    "CorrelationError",
    "DeduplicationError",
    "EnrichmentError",
    "PersistenceError",
    "ExportError",
    "ValidationError",
    "ConfigurationError",
    "OpsecError",
    "RuleLoadError",
    "EntityNotFoundError",
    "DuplicateEntityError",
]
