"""Configurable detection and scoring rule models.

Rules are data, not code. Operators can add Regex, keyword, IOC, YARA, Sigma,
threshold, whitelist, blacklist, and compound rules through configuration or a
future Django administration panel.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class RuleType(StrEnum):
    """Detection rule families supported by the detection engine."""

    REGEX = "regex"
    KEYWORD = "keyword"
    IOC = "ioc"
    YARA = "yara"
    SIGMA = "sigma"
    HEURISTIC = "heuristic"
    WHITELIST = "whitelist"
    BLACKLIST = "blacklist"
    THRESHOLD = "threshold"
    COMPOUND = "compound"


class DetectionRule(BaseModel):
    """Runtime-loaded detection rule."""

    id: UUID = Field(default_factory=uuid4)
    name: str
    type: RuleType
    pattern: str | None = None
    values: list[str] = Field(default_factory=list)
    weight: float = 1.0
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    tags: list[str] = Field(default_factory=list)
    enabled: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


class RuleMatch(BaseModel):
    """Detection result generated by a rule strategy."""

    rule_name: str
    rule_type: RuleType
    value: str
    weight: float
    confidence: float
    tags: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ScoringProfile(BaseModel):
    """Configurable score weights and export threshold."""

    weights: dict[str, float] = Field(default_factory=dict)
    base_score: float = 0.0
    severity_thresholds: dict[str, float] = Field(
        default_factory=lambda: {"low": 10.0, "medium": 35.0, "high": 65.0, "critical": 85.0}
    )
    auto_export_threshold: float = 80.0
